# Generated by Django 5.0.6 on 2024-06-05 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_passworddata_alter_useraccount_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='passworddata',
            name='reg_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 5, 19, 44, 29, 605321), verbose_name='time registered'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='reg_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 5, 19, 44, 29, 605321), verbose_name='time registered'),
        ),
    ]
