# Generated by Django 5.0.6 on 2024-06-05 12:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_user_name_useraccount_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passworddata',
            name='user',
            field=models.ForeignKey(default='test02', on_delete=django.db.models.deletion.CASCADE, to='home.useraccount', to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passworddata',
            name='reg_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 5, 19, 49, 51, 995880), verbose_name='time registered'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='reg_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 5, 19, 49, 51, 995880), verbose_name='time registered'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
