# Generated by Django 5.0.6 on 2024-06-05 16:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_passworddata_user_alter_passworddata_reg_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passworddata',
            name='reg_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 6, 0, 43, 12, 124739), verbose_name='time registered'),
        ),
        migrations.AlterField(
            model_name='passworddata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passworddata', to='home.useraccount', to_field='username'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='reg_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 6, 0, 43, 12, 124739), verbose_name='time registered'),
        ),
    ]
