# Generated by Django 5.0.6 on 2024-06-14 16:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_passworddata_reg_time_alter_passworddata_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='passworddata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passworddata', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passworddata',
            name='reg_time',
            field=models.TimeField(default=datetime.datetime(2024, 6, 15, 0, 25, 38, 418666), verbose_name='time registered'),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
