# Generated by Django 5.0.6 on 2024-06-15 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_passworddata_user_alter_passworddata_reg_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passworddata',
            name='reg_time',
        ),
        migrations.AddField(
            model_name='passworddata',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 6, 15, 22, 46, 18, 687795), verbose_name='date added'),
        ),
    ]
