# Generated by Django 5.0.6 on 2024-06-17 07:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_passworddata_reg_time_passworddata_date_added'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passworddata',
            name='cipher_tag',
            field=models.BinaryField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='passworddata',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 6, 17, 15, 11, 49, 464), verbose_name='date added'),
        ),
        migrations.CreateModel(
            name='KeyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.BinaryField(max_length=32, verbose_name='cipher.nonce')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keydata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
