# Generated by Django 5.0.6 on 2024-06-17 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_passworddata_cipher_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passworddata',
            name='cipher_tag',
            field=models.BinaryField(max_length=32),
        ),
        migrations.AlterField(
            model_name='passworddata',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2024, 6, 17, 21, 30, 12, 902747), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='passworddata',
            name='password',
            field=models.BinaryField(max_length=32),
        ),
    ]
